FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
COPY src ./src
COPY loan_approval_pipeline.onnx .

RUN pip install --no-cache-dir .

CMD ["uvicorn", "deepmlapp.utils.onnx_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]